Add text format attribute for mod configs
Reloaded-Project/Reloaded-II pull request #230
Opened 2023-05-17 13:22 UTC by monkeyman192

Previously for sliders with `double` data type, if you displayed the label it would fluctuate in size wildly because it would show the full un-formatted value.
I have added an extra option so that you can provide a format string.
This makes them much more stable:

![image](https://github.com/Reloaded-Project/Reloaded-II/assets/8000597/04f695ee-f65f-4b3a-87d4-cd11072030ed)

I also tried to make the tooltips a bit nicer by adding a delay to the display, but it didn't really seem to do anything. It's a bit annoying IMO having them over the cursor the whole time while you are trying to drag it as you can't see what the value is while dragging. If you have any suggestions on this I'd appreciate it. I tried a few things but nothing stuck...

2023-05-18 00:11 UTC, monkeyman192 commented
> Question: Any specific reason there's an applied 1 second tooltip delay in this PR?
> 
> Not sure if it's left there for test purposes only, or for any other reason.

From my description:
"I also tried to make the tooltips a bit nicer by adding a delay to the display,"
I'll remove it though since it doesn't seem to really work and as you say, not actually related to the changes I was trying to do...

2023-05-20 02:29 UTC, monkeyman192 commented
Ok, I have removed my changes to the tooltip display time. So it should only have the necessary changes now.

2023-05-20 02:30 UTC, Sewer56 requested changes

2023-05-20 02:30 UTC, Sewer56 commented on source/Testing/Mods/TestModControlParams/TestModControlParams.csproj
> +  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
There's also some leftover automatic additions from your IDE. This should be redundant as OutputPath is set on top of this file.

2023-05-20 02:38 UTC, Sewer56 approved these changes
Alright, looks good to me.

2023-05-20 02:45 UTC, Sewer56 commented
Technically adding a parameter to constructor here breaks backwards compatibility; but I'll just merge it and fix it myself.

2023-05-20 02:46 UTC, merged

2023-05-20 02:47 UTC, monkeyman192 commented
> Technically adding a parameter to constructor here breaks backwards compatibility; but I'll just merge it and fix it myself.

Doesn't giving it a default retain backward compatibility since if not provided it will just do the same behaviour as before?

2023-05-20 02:48 UTC, Sewer56 commented
It would be source backwards compatible, but not binary.
I.e. code compiled against the old constructor would fail, because old constructor no longer exists.

2023-05-20 02:55 UTC, Sewer56 commented
If you're curious; [here's docs on how to resolve it](https://github.com/dotnet/roslyn/blob/main/docs/Adding%20Optional%20Parameters%20in%20Public%20API.md)

I fixed it in d817f78c83f1edf1a231d881d37391c79fba115b

2023-05-20 03:05 UTC, monkeyman192 commented
> If you're curious; [here's docs on how to resolve it](https://github.com/dotnet/roslyn/blob/main/docs/Adding%20Optional%20Parameters%20in%20Public%20API.md)
> 
> I fixed it in [04fbdfa](https://github.com/Reloaded-Project/Reloaded-II/commit/04fbdfa652d1243a2aa615378f5b34d1f6a138ce)

Interesting. Thanks for that.
So if another were to be added it would have to be added at the end and we'd need to have the overload added like you did in that commit?

2023-05-20 03:05 UTC, Sewer56 commented
Yep, pretty much.